services:
  killedby:
    image: bacherik/killedby:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GITHUB_USERNAME=bacherik
      - GITHUB_REPOSITORY=killedby.json
      - UPDATE_TOKEN=testToken
    restart: always

networks:
  default:
    driver: bridge