name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # oder der Name deines Hauptbranches

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.17'  # Wähle die Go-Version

    - name: Build Go project
      run: go build -o ./server ./main.go

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # Das Verzeichnis, das die ausführbare Datei enthält
